%% plot whole path
fN = "C:\Users\valen\Desktop\Correlation_pupil\Cage_GI_traking\GI-00R-WT\20200721_1140-tracker-GI00R.txt";
data = openTrackFile(fN);
[normX, normY] = normalizeCoord(data.x,data.y, data.rect);
plot(normX,normY, 'b');
rectangle('position',[0 0 1 1],...
    'edgeColor','red',...
    'linewidth', 1.5);


%% plot single trial
k = 12; % select trial

data_sep = separateTrials(data);
data_split = splitTrials(data_sep(k));

[normX_sep, normY_sep] = normalizeCoord(data_sep(k).x,data_sep(k).y, data.rect);
[normX_splitPre, normY_splitPre] = normalizeCoord(data_split.Xpre,data_split.Ypre, data.rect);
[normX_splitPost, normY_splitPost] = normalizeCoord(data_split.Xpost,data_split.Ypost, data.rect);
% plot(normX_sep,normY_sep, 'b');
plot(normX_splitPre, normY_splitPre,...
    'color', [0.2539    0.4102    0.8789],...
    'linewidth', 1,...
    'marker', 's',...
    'markerindices', [1 length(normY_splitPre)],...
    'markeredgecolor', 'red');
hold on
plot([normX_splitPre(end); normX_splitPost],[normY_splitPre(end); normY_splitPost],...
    'color', [0    0.9961    0.9961],...
    'linewidth', 1,...
    'marker', 's',...
    'markerindices', length(normY_splitPost),...
    'markeredgecolor', 'red');
hold off
rectangle('position',[0 0 1 1],...
    'edgeColor','red',...
    'linewidth', 1.5);
%% plot only Y position
plot([1:length(normY_splitPre)],normY_splitPre, 'linewidth', 1, 'color', [0.2539    0.4102    0.8789] );
hold on 
plot([length(normY_splitPre):1:length(normY_splitPre)+length(normY_splitPost)],[normY_splitPre(end); normY_splitPost], 'linewidth', 1, 'color', [0    0.9961    0.9961] );
hold off